/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.userstore;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Enumeration of Sponsored Group Roles
 */
public enum SponsoredGroupRole implements TEnum {
  GROUP_MEMBER(1),
  GROUP_ADMIN(2),
  GROUP_OWNER(3);

  private final int value;

  private SponsoredGroupRole(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SponsoredGroupRole findByValue(int value) { 
    switch (value) {
      case 1:
        return GROUP_MEMBER;
      case 2:
        return GROUP_ADMIN;
      case 3:
        return GROUP_OWNER;
      default:
        return null;
    }
  }
}
