/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.type;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.Arrays;

public class Constants {

  public static final String EDAM_NOTE_SOURCE_WEB_CLIP = "web.clip";

  public static final String EDAM_NOTE_SOURCE_MAIL_CLIP = "mail.clip";

  public static final String EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY = "mail.smtp";

}
